on:
  push:
    branches:
      - master







jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: "Login to Docker hub"
        run: docker login --username ahmedsalah12372002 --password ${{secrets.DOCKER_TOKEN}}

      
      - name: "Building Docker image"
        run: docker build -t ahmedsalah12372002/myimage .

      - name: "Pushing to Docker hub"
        run: docker push ahmedsalah12372002/myimage